### ISSUE TITLE
Why is the repo within 'nelsonic' as opposed to 'dwyl'?

### ISSUE THREAD

**Issue by Cleop** [nelsonic/time-mvp-phoenix#2]
@nelsonic I was just wondering why you'd chosen to make this repo inside of your own profile instead of dwyl?

**Comment by nelsonic** [comment]
@Cleop _good_ question!

Answer: Because for now, I'm the one doing the _work_. 
I wrote _all_ of the previous MVP. see: https://github.com/nelsonic/time-mvp/graphs/contributors
and 95% of the one before that: https://github.com/dwyl/time/graphs/contributors 
(_the contribution graph of the main repo does not give a "full picture" of all the **re-useable** modules I created which are still in use today by **many** other projects/companies and get over a million monthly downloads... e.g: https://github.com/dwyl/hapi-auth-jwt2/graphs/contributors ..._) 

99% of the time I _start_ work on a project or "learn-..." repo on my own time/repo 
and then _transfer_ it to @dwyl when there is something to "show". 

As you can see, this repo is _blank_ and only has the "Why" #1  issue. 
I am in the process of [updating my Phoenix Knowledge](https://github.com/nelsonic/practice/issues/55) (["sharpening the saw"](https://en.wikipedia.org/wiki/The_7_Habits_of_Highly_Effective_People#7_-_Sharpen_the_Saw))
Once I feel _confident_ that I can build the app using _all_ of the latest Phoenix best practices, 
I will transfer it. Meanwhile it's 100% open source and and _anyone_ can contribute! 

> This is not a quest for "control", it's more an attempt to avoid "spamming" people with noise.

I suggest that _everyone_ wanting to participate in the Time App (_which will be transferred to @dwyl once there is momentum_) from a technical perspective, re-read the Phoenix book as there are a  number of improvements (_e.g: Contexts_) that we will be applying which are _not_ currently in use in any @dwyl client project(s).

**Comment by nelsonic** [comment]
This "MVP" repo will be integrated into the main https://github.com/dwyl/time once it's got some _useful_ functionality.  👍

**Comment by nelsonic** [comment]
Transferred to: https://github.com/dwyl/app-mvp-phoenix ✅
